languageCode = "en-gb"
title = "DMN developer documentation"
theme = "hugo-material-docs"
publishDir = "../blog-dist"
baseURL = "https://developers.designmynight.com/"
metadataformat = "yaml"
canonifyurls = false
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-12385609-13"

[params]
	# General information
	author = "DesignMyNight Tech Team"
	description = "Developer documentation for DesignMyNight"
	copyright = "DesignMyNight"

	# Repository
	provider = ""
	repo_url = ""

	version = "1.1.0"
	logo = "images/logo.png"
	favicon = "images/favicon.png"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "deep purple"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "designmynight/dmn-developers"

[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 1

[[menu.main]]
    name   = "Collins"
    url    = "collins/"
    identifier = "collins"
	weight = 200

[[menu.main]]
	name   = "Updating Email Settings"
	url    = "collins/updating-email-settings/"
	parent = "collins"
	weight = 205

[[menu.main]]
	name   = "Collins Booking Widget"
	url    = "collins/booking-widget/"
	parent = "collins"
	weight = 210

[[menu.main]]
	name   = "Customer Signup Widget"
	url    = "collins/customer-widget/"
	parent = "collins"
	weight = 215

[[menu.main]]
	name   = "Customising 2nd Iframe"
	url    = "collins/customising-2nd-iframe/"
	parent = "collins"
	weight = 220

[[menu.main]]
	name   = "Booking URLs"
	url    = "collins/booking-url/"
	parent = "collins"
	weight = 225

[[menu.main]]
	name   = "General Enquiry Form"
	url    = "collins/general-enquiry-form/"
	parent = "collins"
	weight = 230

[[menu.main]]
	name   = "Customising Email Templates"
	url    = "collins/customising-email-templates/"
	parent = "collins"
	weight = 235

[[menu.main]]
	name   = "Taking Bookings from Google"
	url    = "collins/taking-bookings-from-google/"
	parent = "collins"
	weight = 240

[[menu.main]]
	name   = "Tracking"
	url    = "collins/tracking/"
	parent = "collins"
	weight = 245


[[menu.main]]
    weight = 299
    name = " "

[[menu.main]]
    weight = 99
    name = "    "

[[menu.main]]
    name   = "Tonic"
    url    = "tonic/"
    identifier = "tonic"
	weight = 100


[[menu.main]]
	name   = "Ticket widget"
	url    = "tonic/ticket-widget/"
	parent = "tonic"
	weight = 101

[[menu.main]]
    weight = 199
    name = "     "

[[menu.main]]
    name   = "Soda"
    url    = "soda/"
    identifier = "soda"
  weight = 100


[[menu.main]]
  name   = "Voucher widget"
  url    = "soda/partner-widget/"
  parent = "soda"
  weight = 101

[[menu.main]]
    weight = 199
    name = "     "

[[menu.main]]
    name   = "API"
    url    = "api/"
    identifier = "API"
	weight = 300

[[menu.main]]
	name   = "API Basics"
	url    = "api/api-basics/"
	weight = 301
	parent = "API"

[[menu.main]]
	name   = "Booking API"
	url    = "api/booking-api/"
	weight = 302
	parent = "API"

[[menu.main]]
	name   = "Bookings search"
	url    = "api/bookings-search/"
	weight = 303
	parent = "API"

[[menu.main]]
    name   = "Users API"
    url    = "api/users-api/"
    weight = 304
	parent = "API"

[[menu.main]]
	name   = "Offers API"
	url    = "api/offers-api/"
	weight = 305
	parent = "API"

[[menu.main]]
	name   = "Venues API"
	url    = "api/venues-api/"
	weight = 306
	parent = "API"

[[menu.main]]
	name   = "Venue Groups API"
	url    = "api/venue-groups/"
	weight = 307
	parent = "API"

[[menu.main]]
	name   = "Event Guests API"
	url    = "api/event-guests-api/"
	weight = 308
	parent = "API"

[[menu.main]]
	name   = "API FAQs"
	url    = "api/api-faqs/"
	weight = 309
	parent = "API"

[[menu.main]]
    weight = 399
    name = "        "

[[menu.main]]
    name   = "EPOS/CRM Integrations"
    url    = "epos-crm-integrations/"
    identifier = "epos-crm-integrations"
	weight = 400

[[menu.main]]
    name   = "Zonal EPOS Integration"
    url    = "epos-crm-integrations/zonal-epos-integration/"
    parent = "epos-crm-integrations"
	weight = 401

[[menu.main]]
    name   = "IBS EPOS Integration"
    url    = "epos-crm-integrations/ibs-epos-integration/"
    parent = "epos-crm-integrations"
	weight = 402
	
[[menu.main]]
    name   = "Tevalis EPOS Integration"
    url    = "epos-crm-integrations/tevalis-epos-integration/"
    parent = "epos-crm-integrations"
	weight = 403

[[menu.main]]
    name   = "CRM Integration"
    url    = "epos-crm-integrations/crm-integration/"
    parent = "epos-crm-integrations"
	weight = 404

[[menu.main]]
    weight = 499
    name = "          "



[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
